#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/home/devuser/.vscode-server/bin/258e40fedc6cb8edf399a463ce3a9d32e7e1f6f3/node" "/home/devuser/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "code --openExternal " "$@"